### ISSUE TITLE
Crash When Rendering Tooltip for Inscription

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [kendrome/kendrome_vh_tweaks#1]
When hovering over the inscription in the Living Chest loot page of JEI, the game crashes. I tested without the mod, and it doesn't crash.

[Crash Log](https://mclo.gs/fdBJX6i)

**Comment by kendrome** [comment]
This should be fixed with https://github.com/kendrome/kendrome_vh_tweaks/releases/tag/v1.0.2, let me know if it's still an issue when you update.

**Comment by BeansBeefBroccoli** [comment]
It works! Thanks!
