### ISSUE TITLE
"ERROR" in Jewel Tooltip after update 3.14.3

### ISSUE THREAD

**Issue by XWutz** [kendrome/kendrome_vh_tweaks#3]
Hello

We Updated our Vault Hunters Version to Update 3.14.3 and after that when I hover over a Jewel the tooltip just shows "ERROR". Maybe something has changed and needs also an Update?

Would be nice to be able to use it again as its function are amazing!

THX

**Comment by kendrome** [comment]
Update should now be available, thanks for letting me know.
[https://www.curseforge.com/minecraft/mc-mods/kendromes-vault-hunters-tweaks/files/5419005](https://www.curseforge.com/minecraft/mc-mods/kendromes-vault-hunters-tweaks/files/5419005)

**Comment by XWutz** [comment]
Hello kendrome!

THANKS for the Update, I do appreciate it a lot! Have a nice one!

Greetings from Germany ^^
