### ISSUE TITLE
Crash to desktop after VH Update 15

### ISSUE THREAD

**Issue by flikamasha89** [kendrome/kendrome_vh_tweaks#5]
When in a workstation if you hover over a vault item you get a CTD. Attached is a crash log.

[crash-2024-08-08_13.59.33-client.txt](https://github.com/user-attachments/files/16562177/crash-2024-08-08_13.59.33-client.txt)

**Comment by flikamasha89** [comment]
Bumping just in case this was missed.

**Comment by kendrome** [comment]
Sorry it took a bit, I have a fix on GitHub and CurseForge should be updated shortly 
https://github.com/kendrome/kendrome_vh_tweaks/releases/tag/v1.2.1
